### ISSUE TITLE
Follow symbolic links

### ISSUE THREAD

**Issue by jberggg** [gbbirkisson/spis#209]
I'm running spis on a linux server and my media folders are located in different paths. I tried to link them into the specified media folder but spis did not follow the symbolic links. I was able to confirm that in the Code as Walkdir does not follow symbolic links by default, one has to specify it with `.follow_links(true)`. Is it possible that you would add that to your next release?

**Comment by gbbirkisson** [comment]
I will look into it when I have time

**Comment by gbbirkisson** [comment]
Will be released with #268

**Comment by jberggg** [comment]
Cool, thank you 🙏🏽
