### ISSUE TITLE
Add password option

### ISSUE THREAD

**Issue by chrisshoto** [gbbirkisson/spis#284]
I really like the interface and simplicity of this tool, and I’ve been using it to manage my photo library, which is hosted on a Synology NAS. My plan was to add password protection using Nginx with a reverse proxy. However, it seems this isn’t easily possible because Nginx doesn’t work well with Synology’s reverse proxy setup.

Would it be possible to add an option for password-protected access?

**Comment by gbbirkisson** [comment]
To keep SPIS as simple as possible, I am hesitant to add this. I think this should be handled by the reverse proxy. Suprised Synology does not support setting up basic auth.

**Comment by chrisshoto** [comment]
Alright, that's unfortunate for me, but I understand your reasoning. I was surprised too regarding Synology. As far as I can tell, you would need to have your own DNS to make it work rather than using the one provided with a Synology NAS.

**Comment by gbbirkisson** [comment]
But do you run the Dockerfile? How are you running SPIS? Can you not configure nginx between Synology and SPIS.

**Comment by chrisshoto** [comment]
Yes, I am running SPIS via the Dockerfile. The issue comes when using the
reverse proxy with Synology to access SPIS. The Synology reverse proxy
implementation already uses nginx and does not allow auth. It also makes it
incompatible with another instance of nginx that could add auth separately.

**Comment by gbbirkisson** [comment]
I see. Well this is a very specific problem, that I will not (at this time) try to fix in SPIS. 99% of the time, people can just configure nginx to handle this, and that is good enough for me.

Closing this issue
