### ISSUE TITLE
Docker image not available

### ISSUE THREAD

**Issue by thomasWos** [gbbirkisson/spis#56]
Hi,
I wanted to try, using the easiest way.

```
docker pull ghcr.io/gbbirkisson/spis:latest
```
```
Error response from daemon: manifest unknown
```

Is the Docker image available?
Cheers

**Comment by gbbirkisson** [comment]
Hi, I never got around pushing the image with the `latest` tag. I will fix that. In the mean time, you can always use the latest version tag:

```console
$ docker pull ghcr.io/gbbirkisson/spis:v0.4.6
```

**Comment by gbbirkisson** [comment]
Fixed, you can now pull the latest image:

```console
$ docker pull ghcr.io/gbbirkisson/spis:latest
```
