### ISSUE TITLE
ERROR: timestamp parsing failed

### ISSUE THREAD

**Issue by han1997** [gbbirkisson/spis#89]
Whether the image with this exception can be displayed normally in the gallery, similar to adding a null tag

**Comment by gbbirkisson** [comment]
> Whether the image with this exception can be displayed normally in the gallery, similar to adding a null tag

Is this a question or a statement?

This error happens when the EXIF data contains strangely formatted (empty string) date data. Attach the actual image to this issue so I can debug it, or use exiftool to extract all the exif data and post it here.

**Comment by gbbirkisson** [comment]
Newest version of `SPIS` will give better error messages, so you should be able to see exactly what the problem is.
