### ISSUE TITLE
Video support in Docker

### ISSUE THREAD

**Issue by spin6lock** [gbbirkisson/spis#94]
Hi, thanks for your work! `To get video support, both ffmpeg and ffprobe must be present in path!` How can I provide ffmpeg and ffprobe in Docker self-host version?

**Comment by gbbirkisson** [comment]
Hey :wave:  

> How can I provide ffmpeg and ffprobe in Docker self-host version?

I assume you are creating your own docker image.

In simple cases it is as easy as installing `ffmpeg` with `apt` (that will also include `ffprobe`). That's how it's done in the "official" docker image in this repo: https://github.com/gbbirkisson/spis/blob/8901c86514db85784a9e9f39424a9d7b5dc48461/docker/Dockerfile#L19

Obviously, if you are using a non-debian based base image, the install process will be different, but I will leave it up to you to figure that out.

Any reason why you are not using the "official" image?

**Comment by spin6lock** [comment]
Oh, I'm using official image, and found that video in H265 can not play in webpage. I just thought that I need to pass in ffmpeg and ffprobe in someway. Or H265 is not support on web instead?
